[package]
name = "ivchenko_pidor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[[bin]]
name = "Sanya"
path = "src/client.rs"

[[bin]]
name = "Peter"
path = "src/server.rs"